use crate::buffer::Offset;
use std::time::Instant;

/// Represents the origin of an edit.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
pub enum Author {
    /// Manually typed by the human developer.
    Human,
    /// Generated by an AI and accepted without changes.
    AiSuggested,
    /// AI-generated code that was later modified by a human.
    AiModified,
}

/// A single atomic edit in the document
#[derive(Debug, Clone)]
pub struct RawEdit {
    pub offset: Offset,
    pub old_text: String,
    pub new_text: String,
    pub cursor_offset: Option<usize>, // Absolute byte offset after all edits
    pub author: Author,               // 🔱 Provenance Tag
}

/// A transaction represents a group of edits across multiple cursors
#[derive(Debug, Clone)]
pub struct Transaction {
    pub edits: Vec<RawEdit>,
    pub cursor_offsets_before: Vec<usize>,
    pub cursor_offsets_after: Vec<usize>,
    pub timestamp: Instant,          // 🕒 Temporal Tracking
}

impl Transaction {
    pub fn new(
        edits: Vec<RawEdit>,
        cursor_offsets_before: Vec<usize>,
        cursor_offsets_after: Vec<usize>,
    ) -> Self {
        Self {
            edits,
            cursor_offsets_before,
            cursor_offsets_after,
            timestamp: Instant::now(),
        }
    }

    pub fn append_edit(&mut self, edit: RawEdit, cursor_after: Vec<usize>) {
        self.edits.push(edit);
        self.cursor_offsets_after = cursor_after;
        self.timestamp = Instant::now(); // Update timestamp on batch modification
    }
}
